Repository n-factorial/news-feed, pull requests merged in 2025-08, with the labels that each got.

#10 feature: implement global api response
  src/main/java/org/nfactorial/newsfeed/common/dto/GlobalApiResponse.java
Labels: feat ✨

#14 feat: implement global exception handling with custom error responses
  src/main/java/org/nfactorial/newsfeed/common/code/ErrorCode.java
  src/main/java/org/nfactorial/newsfeed/common/dto/GlobalApiResponse.java
  src/main/java/org/nfactorial/newsfeed/common/exception/BusinessException.java
  src/main/java/org/nfactorial/newsfeed/common/exception/GlobalExceptionHandler.java
Labels: feat ✨

#27 feat: implement post creation functionality
  build.gradle
  src/main/java/org/nfactorial/newsfeed/NewsFeedApplication.java
  src/main/java/org/nfactorial/newsfeed/common/code/SuccessCode.java
  src/main/java/org/nfactorial/newsfeed/domain/post/controller/PostController.java
  src/main/java/org/nfactorial/newsfeed/domain/post/dto/request/PostCreateRequest.java
  src/main/java/org/nfactorial/newsfeed/domain/post/dto/response/PostCreateResponse.java
  src/main/java/org/nfactorial/newsfeed/domain/post/entity/Post.java
  src/main/java/org/nfactorial/newsfeed/domain/post/mock/MockAuthProfileDto.java
  src/main/java/org/nfactorial/newsfeed/domain/post/repository/PostRepository.java
  src/main/java/org/nfactorial/newsfeed/domain/post/service/PostService.java
  src/main/resources/application.yml
Labels: feat ✨

#29 feat: implement login
  src/main/java/org/nfactorial/newsfeed/common/code/ErrorCode.java
  src/main/java/org/nfactorial/newsfeed/common/code/SuccessCode.java
  src/main/java/org/nfactorial/newsfeed/common/security/AuthProfile.java
  src/main/java/org/nfactorial/newsfeed/common/security/AuthProfileMethodArgResolver.java
  src/main/java/org/nfactorial/newsfeed/common/security/GetProfileFromAccountIdApi.java
  src/main/java/org/nfactorial/newsfeed/common/security/JwtFilter.java
  src/main/java/org/nfactorial/newsfeed/common/security/JwtUtil.java
  src/main/java/org/nfactorial/newsfeed/common/security/mock/GetProfileFromAccountIdService.java
  src/main/java/org/nfactorial/newsfeed/common/security/mock/SecurityMockProfile.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/controller/AuthController.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/dto/LoginCommand.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/dto/LoginRequest.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/dto/LoginResponse.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/mock/AuthMockProfile.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/mock/AuthMockProfileService.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/repository/AccountRepository.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/service/AuthProfileServiceApi.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/service/AuthService.java
  src/test/java/org/nfactorial/newsfeed/domain/auth/controller/AuthControllerIntegrationTest.java
  src/test/java/org/nfactorial/newsfeed/domain/auth/controller/AuthControllerLoginTest.java
Labels: feat ✨

#31 fix: auth sign up
  src/main/java/org/nfactorial/newsfeed/domain/auth/mock/AuthMockProfile.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/mock/AuthMockProfileService.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/service/AuthProfileServiceApi.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/service/AuthService.java
  src/test/java/org/nfactorial/newsfeed/domain/auth/controller/AuthControllerIntegrationTest.java
  src/test/java/org/nfactorial/newsfeed/domain/auth/controller/AuthControllerLoginTest.java
Labels: enhancement

#34 fix: update sign up process to include profiledId and adjust SignUpRe…
  src/main/java/org/nfactorial/newsfeed/domain/auth/dto/SignUpResult.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/entity/Account.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/service/AuthService.java
Labels: enhancement

#36 feat: implemented withdraw
  src/main/java/org/nfactorial/newsfeed/common/code/ErrorCode.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/controller/AuthController.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/dto/SignUpResponse.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/dto/WithdrawRequest.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/entity/Account.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/service/AuthService.java
  src/main/java/org/nfactorial/newsfeed/domain/profile/service/ProfileServiceApi.java
  src/test/java/org/nfactorial/newsfeed/domain/auth/controller/AuthControllerIntegrationTest.java
Labels: feat ✨

#41 feat: implement logout
  src/main/java/org/nfactorial/newsfeed/common/security/JwtFilter.java
  src/main/java/org/nfactorial/newsfeed/common/security/TokenBlacklist.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/controller/AuthController.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/service/AuthService.java
Labels: feat ✨

#46 Feat/post findone
  src/main/java/org/nfactorial/newsfeed/domain/comment/service/CommentServiceApi.java
  src/main/java/org/nfactorial/newsfeed/domain/post/controller/PostController.java
  src/main/java/org/nfactorial/newsfeed/domain/post/dto/response/PostGetOneResponse.java
  src/main/java/org/nfactorial/newsfeed/domain/post/service/PostService.java
Labels: feat ✨

#62 feat: add update comment functionality
  src/main/java/org/nfactorial/newsfeed/domain/comment/controller/CommentController.java
  src/main/java/org/nfactorial/newsfeed/domain/comment/dto/UpdateCommentRequest.java
  src/main/java/org/nfactorial/newsfeed/domain/comment/dto/UpdateCommentResponse.java
  src/main/java/org/nfactorial/newsfeed/domain/comment/entity/Comment.java
  src/main/java/org/nfactorial/newsfeed/domain/comment/service/CommentService.java
Labels: feat ✨

#70 Feat/replace mock profile with real profile data
  src/main/java/org/nfactorial/newsfeed/domain/post/controller/PostController.java
  src/main/java/org/nfactorial/newsfeed/domain/post/entity/Post.java
  src/main/java/org/nfactorial/newsfeed/domain/post/service/PostService.java
  src/main/java/org/nfactorial/newsfeed/domain/post/service/PostServiceApi.java
Labels: feat ✨

#76 feat: add user post count
  src/main/java/org/nfactorial/newsfeed/domain/post/repository/PostRepository.java
Labels: feat ✨

#94 feat(follow): add endpoints to retrieve following profiles
  src/main/java/org/nfactorial/newsfeed/domain/interaction/controller/FollowController.java
  src/main/java/org/nfactorial/newsfeed/domain/interaction/repository/FollowRepository.java
  src/main/java/org/nfactorial/newsfeed/domain/interaction/service/FollowService.java
Labels: feat ✨

#95 Refactor/follow conventions
  src/main/java/org/nfactorial/newsfeed/domain/interaction/controller/FollowController.java
  src/main/java/org/nfactorial/newsfeed/domain/interaction/controller/LikeController.java
  src/main/java/org/nfactorial/newsfeed/domain/interaction/dto/response/FollowStatusResponse.java
  src/main/java/org/nfactorial/newsfeed/domain/interaction/service/FollowService.java
  src/main/java/org/nfactorial/newsfeed/domain/interaction/service/LikeService.java
Labels: enhancement

#88 feat: Implement followed users' feed retrieval
  src/main/java/org/nfactorial/newsfeed/domain/feed/controller/FeedController.java
  src/main/java/org/nfactorial/newsfeed/domain/feed/dto/response/FeedFollowPostProjection.java
  src/main/java/org/nfactorial/newsfeed/domain/feed/dto/response/FeedFollowPostResponse.java
  src/main/java/org/nfactorial/newsfeed/domain/feed/repository/FeedRepository.java
  src/main/java/org/nfactorial/newsfeed/domain/feed/service/FeedService.java
Labels: feat ✨

#96 Feature/account all posts
  src/main/java/org/nfactorial/newsfeed/domain/feed/service/FeedService.java
Labels: feat ✨

#97 fix: circular dependence
  src/main/java/org/nfactorial/newsfeed/domain/comment/controller/CommentController.java
  src/main/java/org/nfactorial/newsfeed/domain/comment/dto/WriteCommentCommand.java
  src/main/java/org/nfactorial/newsfeed/domain/comment/dto/WriteCommentRequest.java
  src/main/java/org/nfactorial/newsfeed/domain/comment/dto/WriteCommentResponse.java
  src/main/java/org/nfactorial/newsfeed/domain/comment/dto/WriteCommentResult.java
  src/main/java/org/nfactorial/newsfeed/domain/comment/service/CommentService.java
  src/main/java/org/nfactorial/newsfeed/domain/comment/service/CommentServiceApi.java
  src/main/java/org/nfactorial/newsfeed/domain/postcomment/controller/PostCommentController.java
  src/main/java/org/nfactorial/newsfeed/domain/postcomment/dto/command/WriteCommentToPostCommand.java
  src/main/java/org/nfactorial/newsfeed/domain/postcomment/dto/request/WriteCommentToPostRequest.java
  src/main/java/org/nfactorial/newsfeed/domain/postcomment/dto/response/GetCommentsFromPostResponse.java
  src/main/java/org/nfactorial/newsfeed/domain/postcomment/dto/response/WriteCommentToPostResponse.java
  src/main/java/org/nfactorial/newsfeed/domain/postcomment/dto/result/CommentListByPostResult.java
  src/main/java/org/nfactorial/newsfeed/domain/postcomment/dto/result/WriteCommentToPostResult.java
  src/main/java/org/nfactorial/newsfeed/domain/postcomment/service/PostCommentService.java
Labels: bug, enhancement

#101 test: Comment E2E test with some fixes.
  src/main/java/org/nfactorial/newsfeed/domain/comment/dto/UpdateCommentRequest.java
  src/main/java/org/nfactorial/newsfeed/domain/postcomment/dto/response/GetCommentsFromPostResponse.java
  src/test/java/org/nfactorial/newsfeed/domain/comment/CommentE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/comment/DeleteCommentE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/comment/GetCommentE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/comment/UpdateCommentE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/comment/WriteCommentE2ETest.java
Labels: bug, enhancement

#104 fix: Enhance password policy
  src/main/java/org/nfactorial/newsfeed/common/code/ErrorCode.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/AuthConstants.java
  src/main/java/org/nfactorial/newsfeed/domain/auth/service/AuthService.java
  src/test/java/org/nfactorial/newsfeed/domain/auth/AuthRequiredE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/auth/LoginE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/auth/SignUpE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/comment/DeleteCommentE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/comment/GetCommentE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/comment/UpdateCommentE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/comment/WriteCommentE2ETest.java
Labels: bug, enhancement

#107 fix: Ensure Post and Profile relationships are mandatory in Comment e…
  src/main/java/org/nfactorial/newsfeed/domain/comment/entity/Comment.java
Labels: enhancement

#106 feat: add date range filter for all-posts
  src/main/java/org/nfactorial/newsfeed/domain/feed/dto/request/FeedPageRequest.java
  src/main/java/org/nfactorial/newsfeed/domain/feed/repository/FeedRepository.java
  src/main/java/org/nfactorial/newsfeed/domain/feed/service/FeedService.java
Labels: feat ✨

#110 fix: Ensure non-null response body in auth E2E tests and correct GlobalApiResponse generic type
  src/main/java/org/nfactorial/newsfeed/common/dto/GlobalApiResponse.java
  src/test/java/org/nfactorial/newsfeed/domain/auth/AuthRequiredE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/auth/LoginE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/auth/SignUpE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/comment/CommentE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/comment/GetCommentE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/comment/UpdateCommentE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/comment/WriteCommentE2ETest.java
Labels: enhancement

#115 Feat/post view count
  src/main/java/org/nfactorial/newsfeed/domain/interaction/service/InteractionQueryService.java
  src/main/java/org/nfactorial/newsfeed/domain/post/controller/PostController.java
  src/main/java/org/nfactorial/newsfeed/domain/post/dto/response/PostGetOneResponse.java
  src/main/java/org/nfactorial/newsfeed/domain/post/entity/Post.java
  src/main/java/org/nfactorial/newsfeed/domain/post/repository/PostRepository.java
  src/main/java/org/nfactorial/newsfeed/domain/post/service/PostService.java
Labels: feat ✨

#116 feat: add all-posts view count response and update query
  src/main/java/org/nfactorial/newsfeed/domain/feed/dto/response/FeedAccountPostProjection.java
  src/main/java/org/nfactorial/newsfeed/domain/feed/dto/response/FeedFollowPostProjection.java
  src/main/java/org/nfactorial/newsfeed/domain/feed/dto/response/FeedFollowPostResponse.java
  src/main/java/org/nfactorial/newsfeed/domain/feed/dto/response/FeedResponse.java
  src/main/java/org/nfactorial/newsfeed/domain/feed/dto/response/FeedResponseProjection.java
  src/main/java/org/nfactorial/newsfeed/domain/feed/dto/response/FeedSpecificResponse.java
  src/main/java/org/nfactorial/newsfeed/domain/feed/repository/FeedRepository.java
  src/main/java/org/nfactorial/newsfeed/domain/feed/service/FeedService.java
Labels: feat ✨

#117 refactor: Decouple controller and entities
  src/main/java/org/nfactorial/newsfeed/domain/commenting/service/PostCommentService.java
  src/main/java/org/nfactorial/newsfeed/domain/feed/service/FeedService.java
  src/main/java/org/nfactorial/newsfeed/domain/interaction/service/FollowService.java
  src/main/java/org/nfactorial/newsfeed/domain/interaction/service/InteractionQueryService.java
  src/main/java/org/nfactorial/newsfeed/domain/interaction/service/LikeService.java
  src/main/java/org/nfactorial/newsfeed/domain/post/controller/PostController.java
  src/main/java/org/nfactorial/newsfeed/domain/post/repository/PostRepository.java
  src/main/java/org/nfactorial/newsfeed/domain/post/service/PostCreationService.java
  src/main/java/org/nfactorial/newsfeed/domain/post/service/PostInteractionService.java
  src/main/java/org/nfactorial/newsfeed/domain/post/service/PostService.java
  src/main/java/org/nfactorial/newsfeed/domain/post/service/PostServiceApi.java
  src/main/java/org/nfactorial/newsfeed/domain/profile/controller/ProfileController.java
  src/main/java/org/nfactorial/newsfeed/domain/profile/dto/response/ProfileResponse.java
  src/main/java/org/nfactorial/newsfeed/domain/profile/repository/ProfileRepository.java
  src/main/java/org/nfactorial/newsfeed/domain/profile/service/ProfileService.java
  src/main/java/org/nfactorial/newsfeed/domain/profile/service/ProfileServiceApi.java
Labels: enhancement

#120 feat: add post counting methods for single and multiple profiles
  src/main/java/org/nfactorial/newsfeed/domain/post/service/PostService.java
Labels: feat ✨

#124 chore: Write README.md to present our project.
  README.md
  erd.png
Labels: documentation

#133 revert: "refactor: Remove internal-only method signatures from ProfileServiceApi."
  src/main/java/org/nfactorial/newsfeed/domain/profile/service/ProfileService.java
  src/main/java/org/nfactorial/newsfeed/domain/profile/service/ProfileServiceApi.java
Labels: enhancement

#134 refactor: Remove internal-only method signatures from ProfileServiceApi.
  src/main/java/org/nfactorial/newsfeed/domain/profile/service/ProfileService.java
  src/main/java/org/nfactorial/newsfeed/domain/profile/service/ProfileServiceApi.java
Labels: enhancement

#136 fix: Add OneToMany between post and comment for delete.
  src/main/java/org/nfactorial/newsfeed/domain/post/entity/Post.java
  src/test/java/org/nfactorial/newsfeed/domain/post/DeletePostWithCommentE2ETest.java
  src/test/java/org/nfactorial/newsfeed/domain/post/PostE2ETest.java
Labels: bug
